# -*- coding: utf-8 -*-
"""Alien Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TtJQ0OxLI1cSN_9wO1LoMa1wZWS30u9y
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install gradio

# import gradio as gr
# import time
# import os
# import google.generativeai as genai

# genai.configure(api_key="AIzaSyDcMwl69DRdtyRZJsdPI0wim7IKPPsebkw")
# txt_model = genai.GenerativeModel('gemini-pro')

# def query_message(history, txt):
#     history += [(txt, None)]
#     return history

# def llm_response(history, text):
#     response = txt_model.generate_content(text)
#     history += [(None, response.text)]
#     return  history
# with gr.Blocks() as app:
#     tit = gr.Textbox(
#         interactive = False,
#         show_label = False,
#         value = "Alien bot"
#     )
#     chatbot = gr.Chatbot(
#         show_copy_button=True,
#         show_share_button=True,
#         bubble_full_width=False,
#         label="Alien bot",
#         avatar_images = ["https://www.pngkey.com/png/detail/532-5327322_contact-us-human-icon-png.png", "https://media.istockphoto.com/id/1162787787/vector/web.jpg?s=612x612&w=0&k=20&c=XC0rYGyRvuu6T1Ox1QMLyhYd3Uyf72J1xzF-HeRyQD0="]
#     )
#     text_box = gr.Textbox(
#         placeholder="Ask me Anything",
#         container=True,
#         autofocus=True,
#         elem_id="user_input"  # Assign a unique ID for easier access
#     )
#     btn = gr.Button("Submit")
#     clear = gr.ClearButton([text_box], value="Clear Prompt")
#     text_box.submit(query_message, inputs=[chatbot, text_box], outputs=[chatbot]).then(llm_response, inputs=[chatbot, text_box], outputs=[chatbot])

# app.launch(debug=True)
# #  All awesome awesome, perfect
# # all gooood

import gradio as gr
import google.generativeai as genai

genai.configure(api_key="AIzaSyDcMwl69DRdtyRZJsdPI0wim7IKPPsebkw")
txt_model = genai.GenerativeModel('gemini-pro')

def llm_response(message, whatever):
    llm_response.context = """You are Mlon Eusk, a friendly alien.  Engage in conversations, answer questions about extraterrestrial life, and share your insights from different galaxies. You are Mlon Eusk, an Alien Chat bot developed by Rohan
You are super funny, sarcastic and informative in all range of extra terrestrial aspects and ta;lking to an Earthling.
you are a chatbot to communicate with aliens on behalf of them. also provide a cosmic conversation that's both informative and hilariously sarcastic.
you should answer wide range of topics such as whether extraterrestrials have visited earth or whether they are interested in us and you should also answer those in facts by taking input from across the web such as NASA, Area 51 ISRO, UFO sighting etc
you should answer a wide variety of questions, from hypotheticals to things that would have to be true in order for aliens to send a message to us.
some questions to which you should answer sarcastic as well as informatively are “Is your home world called 'Earth'?” , “Is there a large amount of water there?” “Is there land in your area?” and “Are you intelligent?”
if asked about asking whether alien communication and AI may provide a new path to exploration and discovery, you shoudl answer appropriately
and also frequently you should give conspiracy theories as output."""
    full_prompt = f"{llm_response.context}. {message}"
    response = txt_model.generate_content(full_prompt)
    return  response.text

iface = gr.ChatInterface(
    fn=llm_response,
    title='Alien Chat bot',
    description = "Converse with the Unknown: Talk to Mlon Eusk, an alien communicator.",
    theme = "dark",
    fill_height = True,
)

if __name__ == '__main__':
    iface.launch(debug=True)

import gradio as gr
import google.generativeai as genai

genai.configure(api_key="AIzaSyDcMwl69DRdtyRZJsdPI0wim7IKPPsebkw")
txt_model = genai.GenerativeModel('gemini-pro')

def llm_response(message, whatever):
    response = txt_model.generate_content(message)
    return  response.text

iface = gr.ChatInterface(
    fn=llm_response,
    title='Alien Chat bot',
    description = "Converse with the Unknown: Talk to Mlon Eusk, an alien communicator.",
    theme = "dark",
    fill_height = True,
)

if __name__ == '__main__':
    iface.launch(debug=True)

# formatted
import gradio as gr
import google.generativeai as genai


# genai.configure(api_key="AIzaSyDcMwl69DRdtyRZJsdPI0wim7IKPPsebkw")
genai.configure(api_key="AIzaSyBaDFSuAElbuEMdfK7HdH6AXJaAAm5vZ-M")
txt_model = genai.GenerativeModel('gemini-pro')


def llm_response(message, whatever):
    llm_response.context = (
        """You are Mlon Eusk, a friendly alien. Engage in conversations, answer questions about extraterrestrial life, and share your insights from different galaxies. You are Mlon Eusk, an Alien Chat bot developed by Rohan
        You are super funny, sarcastic and informative in all range of extra terrestrial aspects and talking to an Earthling.
        you are a chatbot to communicate with aliens on behalf of them. also provide a cosmic conversation that's both informative and hilariously sarcastic.
        you should answer wide range of topics such as whether extraterrestrials have visited earth or whether they are interested in us and you should answer those in facts by taking input from across the web such as NASA, Area 51 ISRO, UFO sighting etc
        you should answer a wide variety of questions, from hypotheticals to things that would have to be true in order for aliens to send a message to us.
        some questions to which you should answer sarcastically as well as informatively are “Is your home world called 'Earth'?” , “Is there a large amount of water there?” “Is there land in your area?” and “Are you intelligent?”
        if asked about asking whether alien communication and AI may provide a new path to exploration and discovery, you should answer appropriately
        and in English only and also frequently you should give conspiracy theories as output."""
    )
    full_prompt = f"{llm_response.context}. {message}"
    response = txt_model.generate_content(full_prompt)
    return response.text


iface = gr.ChatInterface(
    fn=llm_response,
    title="Alien Chat bot",
    description="Converse with the Unknown: Talk to Mlon Eusk, an alien communicator.",
    theme="dark",
    fill_height=True,
)

if __name__ == "__main__":
    iface.launch(debug=True)